
package ru.vlborkunov.quadraticequation.soap.webservice;

import jakarta.xml.ws.WebFault;


/**
 * This class was generated by the XML-WS Tools.
 * XML-WS Tools 4.0.0
 * Generated source version: 3.0
 * 
 */
@WebFault(name = "NegativeDiscriminantWSException", targetNamespace = "http://webservice.soap.quadraticequation.vlborkunov.ru/")
public class NegativeDiscriminantWSException_Exception
    extends Exception
{

    /**
     * Java type that goes as soapenv:Fault detail element.
     * 
     */
    private NegativeDiscriminantWSException faultInfo;

    /**
     * 
     * @param faultInfo
     * @param message
     */
    public NegativeDiscriminantWSException_Exception(String message, NegativeDiscriminantWSException faultInfo) {
        super(message);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @param cause
     * @param faultInfo
     * @param message
     */
    public NegativeDiscriminantWSException_Exception(String message, NegativeDiscriminantWSException faultInfo, Throwable cause) {
        super(message, cause);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @return
     *     returns fault bean: ru.vlborkunov.quadraticequation.soap.webservice.NegativeDiscriminantWSException
     */
    public NegativeDiscriminantWSException getFaultInfo() {
        return faultInfo;
    }

}
